# Generated by Django 5.2 on 2025-05-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_boleta_carrito_itemcarrito_ordendespacho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='total',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ordendespacho',
            name='boleta',
        ),
        migrations.RemoveField(
            model_name='ordendespacho',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='ordendespacho',
            name='entregado',
        ),
        migrations.AddField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='ordendespacho',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', max_length=10),
        ),
    ]
